{
 "title": "custom-dashbord-Nava",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Using Memory - juice-shop-pods",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"recipe-app\", container!=\"POD\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Using CPU: juice-shop-pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"recipe-app\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Remaining (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes / node_filesystem_size_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic (sent and received)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"recipe-app\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}