{
 "title": "custom-dashbord-Nava",
 "time": { "from": "2025-01-23T14:03:44.943Z", "to": "2025-01-24T02:03:44.943Z" },
 "panels": [
  {
   "title": "CPU usage on each node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\n  rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])\n  * on (instance) group_left(node)\n  label_replace(\n    count by (instance) (node_filesystem_avail_bytes{device!~\"tmpfs|shm\"}),\n    \"node\",\n    \"$1\",\n    \"instance\",\n    \"(.*):.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Using CPU: mongodb-pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{namespace=\"recipe-app\", pod=~\"recipe-app-mongodb.*\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Using Memory - mongodb-pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_usage_bytes{namespace=\"recipe-app\", pod=~\"recipe-app-mongodb.*\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total available disk space (in bytes) for each node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\n  label_replace(\n    node_filesystem_avail_bytes{device!~\"tmpfs|shm\"},\n    \"node\",\n    \"$1\",\n    \"instance\",\n    \"(.*):.*\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}